six_susp:
  # Publish joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000 

  # LEG effort Controllers ---------------------------------------
  leg_fr_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_leg_fr

  leg_mr_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_leg_mr

  leg_br_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_leg_br

  leg_fl_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_leg_fl

  leg_ml_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_leg_ml

  leg_bl_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_leg_bl

  # WHEEL effort Controllers ---------------------------------------
  wheel_fr_effort_controller:
    type: effort_controllers/JointEffortController
    joint: leg_fr_wheel_fr

  wheel_mr_effort_controller:
    type: effort_controllers/JointEffortController
    joint: leg_mr_wheel_mr

  wheel_br_effort_controller:
    type: effort_controllers/JointEffortController
    joint: leg_br_wheel_br

  wheel_fl_effort_controller:
    type: effort_controllers/JointEffortController
    joint: leg_fl_wheel_fl

  wheel_ml_effort_controller:
    type: effort_controllers/JointEffortController
    joint: leg_ml_wheel_ml

  wheel_bl_effort_controller:
    type: effort_controllers/JointEffortController
    joint: leg_bl_wheel_bl

